# Generated by Django 4.1.3 on 2022-11-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Фамилия и имя')),
                ('description', models.TextField(blank=True, verbose_name='Биография')),
                ('image', models.ImageField(upload_to='image/directions/%Y', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Режиссер',
                'verbose_name_plural': 'Режиссеры',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название жанра')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('url', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AddField(
            model_name='film',
            name='url',
            field=models.SlugField(default='comedy', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='film',
            name='imag',
            field=models.ImageField(upload_to='image/%Y', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название фильма'),
        ),
        migrations.AddField(
            model_name='film',
            name='directions',
            field=models.ManyToManyField(to='films.direction', verbose_name='Режиссеры'),
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(to='films.genre', verbose_name='Жанры'),
        ),
    ]
